run:
  issues-exit-code: 4
  tests: true
  skip-dirs:
    - src/mocks
  go: '1.18'

output:
  print-linter-name: true
  sort-results: true
  format: tab
  print-issued-lines: false

linters:
  disable-all: true
  enable:
    - asciicheck
    - bidichk
    - containedctx
    - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - grouper
    - ifshort
    - importas
    - ineffassign
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - termliatelle
    - tenv
    - testpackage
    - typecheck
    - unconvert
    - varcheck
    - whitespace
    - wrapcheck
    - wsl

linters-settings:
  lll:
    line-length: 140
  gomnd:
    ignored-functions:
      - 'flag.FlagSet'
      - 'strconv.ParseUint'
      - 'cobra.ExactArgs'
      - 'make'