run:
  issues-exit-code: 4
  tests: true
  skip-dirs:
    - src/mocks
  go: '1.23'

output:
  print-linter-name: true
  sort-results: true
  format: tab
  print-issued-lines: false

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - intrange
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  lll:
    line-length: 140
  gomnd:
    ignored-functions:
      - 'flag.FlagSet'
      - 'strconv.ParseUint'
      - 'cobra.ExactArgs'
      - 'make'
