// Code generated by entc, DO NOT EDIT.

package relation

import (
	"time"
)

const (
	// Label holds the string label denoting the relation type in the database.
	Label = "relation"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTagID holds the string denoting the tag_id field in the database.
	FieldTagID = "tag_id"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldNamespaceID holds the string denoting the namespace_id field in the database.
	FieldNamespaceID = "namespace_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTag holds the string denoting the tag edge name in mutations.
	EdgeTag = "tag"
	// EdgeNamespace holds the string denoting the namespace edge name in mutations.
	EdgeNamespace = "namespace"
	// Table holds the table name of the relation in the database.
	Table = "relations"
	// TagTable is the table that holds the tag relation/edge.
	TagTable = "relations"
	// TagInverseTable is the table name for the Tag entity.
	// It exists in this package in order to avoid circular dependency with the "tag" package.
	TagInverseTable = "tags"
	// TagColumn is the table column denoting the tag relation/edge.
	TagColumn = "tag_id"
	// NamespaceTable is the table that holds the namespace relation/edge.
	NamespaceTable = "relations"
	// NamespaceInverseTable is the table name for the Namespace entity.
	// It exists in this package in order to avoid circular dependency with the "namespace" package.
	NamespaceInverseTable = "namespaces"
	// NamespaceColumn is the table column denoting the namespace relation/edge.
	NamespaceColumn = "namespace_id"
)

// Columns holds all SQL columns for relation fields.
var Columns = []string{
	FieldID,
	FieldTagID,
	FieldEntityID,
	FieldNamespaceID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TagIDValidator is a validator for the "tag_id" field. It is called by the builders before save.
	TagIDValidator func(int) error
	// EntityIDValidator is a validator for the "entity_id" field. It is called by the builders before save.
	EntityIDValidator func(int) error
	// NamespaceIDValidator is a validator for the "namespace_id" field. It is called by the builders before save.
	NamespaceIDValidator func(int) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)
