// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Namespace is the predicate function for namespace builders.
type Namespace func(*sql.Selector)

// Relation is the predicate function for relation builders.
type Relation func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
