// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/dmalykh/tagservice/repository/entgo/ent/namespace"
	"github.com/dmalykh/tagservice/repository/entgo/ent/relation"
	"github.com/dmalykh/tagservice/repository/entgo/ent/tag"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RelationCreate is the builder for creating a Relation entity.
type RelationCreate struct {
	config
	mutation *RelationMutation
	hooks    []Hook
}

// SetTagID sets the "tag_id" field.
func (rc *RelationCreate) SetTagID(i int) *RelationCreate {
	rc.mutation.SetTagID(i)
	return rc
}

// SetEntityID sets the "entity_id" field.
func (rc *RelationCreate) SetEntityID(i int) *RelationCreate {
	rc.mutation.SetEntityID(i)
	return rc
}

// SetNamespaceID sets the "namespace_id" field.
func (rc *RelationCreate) SetNamespaceID(i int) *RelationCreate {
	rc.mutation.SetNamespaceID(i)
	return rc
}

// SetCreatedAt sets the "created_at" field.
func (rc *RelationCreate) SetCreatedAt(t time.Time) *RelationCreate {
	rc.mutation.SetCreatedAt(t)
	return rc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (rc *RelationCreate) SetNillableCreatedAt(t *time.Time) *RelationCreate {
	if t != nil {
		rc.SetCreatedAt(*t)
	}
	return rc
}

// SetTag sets the "tag" edge to the Tag entity.
func (rc *RelationCreate) SetTag(t *Tag) *RelationCreate {
	return rc.SetTagID(t.ID)
}

// SetNamespace sets the "namespace" edge to the Namespace entity.
func (rc *RelationCreate) SetNamespace(n *Namespace) *RelationCreate {
	return rc.SetNamespaceID(n.ID)
}

// Mutation returns the RelationMutation object of the builder.
func (rc *RelationCreate) Mutation() *RelationMutation {
	return rc.mutation
}

// Save creates the Relation in the database.
func (rc *RelationCreate) Save(ctx context.Context) (*Relation, error) {
	var (
		err  error
		node *Relation
	)
	rc.defaults()
	if len(rc.hooks) == 0 {
		if err = rc.check(); err != nil {
			return nil, err
		}
		node, err = rc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RelationMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = rc.check(); err != nil {
				return nil, err
			}
			rc.mutation = mutation
			if node, err = rc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(rc.hooks) - 1; i >= 0; i-- {
			if rc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = rc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rc *RelationCreate) SaveX(ctx context.Context) *Relation {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *RelationCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *RelationCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *RelationCreate) defaults() {
	if _, ok := rc.mutation.CreatedAt(); !ok {
		v := relation.DefaultCreatedAt()
		rc.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *RelationCreate) check() error {
	if _, ok := rc.mutation.TagID(); !ok {
		return &ValidationError{Name: "tag_id", err: errors.New(`ent: missing required field "Relation.tag_id"`)}
	}
	if v, ok := rc.mutation.TagID(); ok {
		if err := relation.TagIDValidator(v); err != nil {
			return &ValidationError{Name: "tag_id", err: fmt.Errorf(`ent: validator failed for field "Relation.tag_id": %w`, err)}
		}
	}
	if _, ok := rc.mutation.EntityID(); !ok {
		return &ValidationError{Name: "entity_id", err: errors.New(`ent: missing required field "Relation.entity_id"`)}
	}
	if v, ok := rc.mutation.EntityID(); ok {
		if err := relation.EntityIDValidator(v); err != nil {
			return &ValidationError{Name: "entity_id", err: fmt.Errorf(`ent: validator failed for field "Relation.entity_id": %w`, err)}
		}
	}
	if _, ok := rc.mutation.NamespaceID(); !ok {
		return &ValidationError{Name: "namespace_id", err: errors.New(`ent: missing required field "Relation.namespace_id"`)}
	}
	if v, ok := rc.mutation.NamespaceID(); ok {
		if err := relation.NamespaceIDValidator(v); err != nil {
			return &ValidationError{Name: "namespace_id", err: fmt.Errorf(`ent: validator failed for field "Relation.namespace_id": %w`, err)}
		}
	}
	if _, ok := rc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Relation.created_at"`)}
	}
	if _, ok := rc.mutation.TagID(); !ok {
		return &ValidationError{Name: "tag", err: errors.New(`ent: missing required edge "Relation.tag"`)}
	}
	if _, ok := rc.mutation.NamespaceID(); !ok {
		return &ValidationError{Name: "namespace", err: errors.New(`ent: missing required edge "Relation.namespace"`)}
	}
	return nil
}

func (rc *RelationCreate) sqlSave(ctx context.Context) (*Relation, error) {
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (rc *RelationCreate) createSpec() (*Relation, *sqlgraph.CreateSpec) {
	var (
		_node = &Relation{config: rc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: relation.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: relation.FieldID,
			},
		}
	)
	if value, ok := rc.mutation.EntityID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: relation.FieldEntityID,
		})
		_node.EntityID = value
	}
	if value, ok := rc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: relation.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if nodes := rc.mutation.TagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   relation.TagTable,
			Columns: []string{relation.TagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: tag.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TagID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rc.mutation.NamespaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   relation.NamespaceTable,
			Columns: []string{relation.NamespaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: namespace.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.NamespaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RelationCreateBulk is the builder for creating many Relation entities in bulk.
type RelationCreateBulk struct {
	config
	builders []*RelationCreate
}

// Save creates the Relation entities in the database.
func (rcb *RelationCreateBulk) Save(ctx context.Context) ([]*Relation, error) {
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Relation, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RelationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *RelationCreateBulk) SaveX(ctx context.Context) []*Relation {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *RelationCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *RelationCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
